# Generated by Django 4.2.5 on 2023-10-13 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_img', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=4)),
                ('motor', models.CharField(max_length=50)),
                ('kilometragem', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caracteristica', models.CharField(max_length=30)),
                ('id_carrro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carros.carros')),
            ],
        ),
    ]
