# Generated by Django 4.2.5 on 2023-10-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carros', '0002_remove_caracteristicas_id_caracteristicas_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicas',
            old_name='id_carrro',
            new_name='id_carro',
        ),
    ]
